/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SaliRouteImport } from './routes/sali'
import { Route as ResetParolaRouteImport } from './routes/reset-parola'
import { Route as ProprietarRouteImport } from './routes/proprietar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmareRouteImport } from './routes/confirmare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaliIndexRouteImport } from './routes/sali.index'
import { Route as ProprietarIndexRouteImport } from './routes/proprietar.index'
import { Route as SaliSlugRouteImport } from './routes/sali.$slug'
import { Route as RezervaSlugRouteImport } from './routes/rezerva.$slug'
import { Route as ProprietarSaliRouteImport } from './routes/proprietar.sali'
import { Route as ProprietarDashboardRouteImport } from './routes/proprietar.dashboard'
import { Route as ProprietarCalendarRouteImport } from './routes/proprietar.calendar'
import { Route as ProprietarSaliIndexRouteImport } from './routes/proprietar.sali.index'
import { Route as ProprietarSaliNouRouteImport } from './routes/proprietar.sali.nou'
import { Route as ProprietarSaliIdRouteImport } from './routes/proprietar.sali.$id'
import { Route as ProprietarSaliIdEditRouteImport } from './routes/proprietar.sali.$id.edit'
import { Route as ProprietarSaliIdCalendarRouteImport } from './routes/proprietar.sali.$id.calendar'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SaliRoute = SaliRouteImport.update({
  id: '/sali',
  path: '/sali',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetParolaRoute = ResetParolaRouteImport.update({
  id: '/reset-parola',
  path: '/reset-parola',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarRoute = ProprietarRouteImport.update({
  id: '/proprietar',
  path: '/proprietar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmareRoute = ConfirmareRouteImport.update({
  id: '/confirmare',
  path: '/confirmare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaliIndexRoute = SaliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaliRoute,
} as any)
const ProprietarIndexRoute = ProprietarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProprietarRoute,
} as any)
const SaliSlugRoute = SaliSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SaliRoute,
} as any)
const RezervaSlugRoute = RezervaSlugRouteImport.update({
  id: '/rezerva/$slug',
  path: '/rezerva/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarSaliRoute = ProprietarSaliRouteImport.update({
  id: '/sali',
  path: '/sali',
  getParentRoute: () => ProprietarRoute,
} as any)
const ProprietarDashboardRoute = ProprietarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProprietarRoute,
} as any)
const ProprietarCalendarRoute = ProprietarCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ProprietarRoute,
} as any)
const ProprietarSaliIndexRoute = ProprietarSaliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProprietarSaliRoute,
} as any)
const ProprietarSaliNouRoute = ProprietarSaliNouRouteImport.update({
  id: '/nou',
  path: '/nou',
  getParentRoute: () => ProprietarSaliRoute,
} as any)
const ProprietarSaliIdRoute = ProprietarSaliIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProprietarSaliRoute,
} as any)
const ProprietarSaliIdEditRoute = ProprietarSaliIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProprietarSaliIdRoute,
} as any)
const ProprietarSaliIdCalendarRoute =
  ProprietarSaliIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => ProprietarSaliIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmare': typeof ConfirmareRoute
  '/login': typeof LoginRoute
  '/proprietar': typeof ProprietarRouteWithChildren
  '/reset-parola': typeof ResetParolaRoute
  '/sali': typeof SaliRouteWithChildren
  '/signup': typeof SignupRoute
  '/proprietar/calendar': typeof ProprietarCalendarRoute
  '/proprietar/dashboard': typeof ProprietarDashboardRoute
  '/proprietar/sali': typeof ProprietarSaliRouteWithChildren
  '/rezerva/$slug': typeof RezervaSlugRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/proprietar/': typeof ProprietarIndexRoute
  '/sali/': typeof SaliIndexRoute
  '/proprietar/sali/$id': typeof ProprietarSaliIdRouteWithChildren
  '/proprietar/sali/nou': typeof ProprietarSaliNouRoute
  '/proprietar/sali/': typeof ProprietarSaliIndexRoute
  '/proprietar/sali/$id/calendar': typeof ProprietarSaliIdCalendarRoute
  '/proprietar/sali/$id/edit': typeof ProprietarSaliIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmare': typeof ConfirmareRoute
  '/login': typeof LoginRoute
  '/reset-parola': typeof ResetParolaRoute
  '/signup': typeof SignupRoute
  '/proprietar/calendar': typeof ProprietarCalendarRoute
  '/proprietar/dashboard': typeof ProprietarDashboardRoute
  '/rezerva/$slug': typeof RezervaSlugRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/proprietar': typeof ProprietarIndexRoute
  '/sali': typeof SaliIndexRoute
  '/proprietar/sali/$id': typeof ProprietarSaliIdRouteWithChildren
  '/proprietar/sali/nou': typeof ProprietarSaliNouRoute
  '/proprietar/sali': typeof ProprietarSaliIndexRoute
  '/proprietar/sali/$id/calendar': typeof ProprietarSaliIdCalendarRoute
  '/proprietar/sali/$id/edit': typeof ProprietarSaliIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmare': typeof ConfirmareRoute
  '/login': typeof LoginRoute
  '/proprietar': typeof ProprietarRouteWithChildren
  '/reset-parola': typeof ResetParolaRoute
  '/sali': typeof SaliRouteWithChildren
  '/signup': typeof SignupRoute
  '/proprietar/calendar': typeof ProprietarCalendarRoute
  '/proprietar/dashboard': typeof ProprietarDashboardRoute
  '/proprietar/sali': typeof ProprietarSaliRouteWithChildren
  '/rezerva/$slug': typeof RezervaSlugRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/proprietar/': typeof ProprietarIndexRoute
  '/sali/': typeof SaliIndexRoute
  '/proprietar/sali/$id': typeof ProprietarSaliIdRouteWithChildren
  '/proprietar/sali/nou': typeof ProprietarSaliNouRoute
  '/proprietar/sali/': typeof ProprietarSaliIndexRoute
  '/proprietar/sali/$id/calendar': typeof ProprietarSaliIdCalendarRoute
  '/proprietar/sali/$id/edit': typeof ProprietarSaliIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmare'
    | '/login'
    | '/proprietar'
    | '/reset-parola'
    | '/sali'
    | '/signup'
    | '/proprietar/calendar'
    | '/proprietar/dashboard'
    | '/proprietar/sali'
    | '/rezerva/$slug'
    | '/sali/$slug'
    | '/proprietar/'
    | '/sali/'
    | '/proprietar/sali/$id'
    | '/proprietar/sali/nou'
    | '/proprietar/sali/'
    | '/proprietar/sali/$id/calendar'
    | '/proprietar/sali/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmare'
    | '/login'
    | '/reset-parola'
    | '/signup'
    | '/proprietar/calendar'
    | '/proprietar/dashboard'
    | '/rezerva/$slug'
    | '/sali/$slug'
    | '/proprietar'
    | '/sali'
    | '/proprietar/sali/$id'
    | '/proprietar/sali/nou'
    | '/proprietar/sali'
    | '/proprietar/sali/$id/calendar'
    | '/proprietar/sali/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/confirmare'
    | '/login'
    | '/proprietar'
    | '/reset-parola'
    | '/sali'
    | '/signup'
    | '/proprietar/calendar'
    | '/proprietar/dashboard'
    | '/proprietar/sali'
    | '/rezerva/$slug'
    | '/sali/$slug'
    | '/proprietar/'
    | '/sali/'
    | '/proprietar/sali/$id'
    | '/proprietar/sali/nou'
    | '/proprietar/sali/'
    | '/proprietar/sali/$id/calendar'
    | '/proprietar/sali/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmareRoute: typeof ConfirmareRoute
  LoginRoute: typeof LoginRoute
  ProprietarRoute: typeof ProprietarRouteWithChildren
  ResetParolaRoute: typeof ResetParolaRoute
  SaliRoute: typeof SaliRouteWithChildren
  SignupRoute: typeof SignupRoute
  RezervaSlugRoute: typeof RezervaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sali': {
      id: '/sali'
      path: '/sali'
      fullPath: '/sali'
      preLoaderRoute: typeof SaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-parola': {
      id: '/reset-parola'
      path: '/reset-parola'
      fullPath: '/reset-parola'
      preLoaderRoute: typeof ResetParolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietar': {
      id: '/proprietar'
      path: '/proprietar'
      fullPath: '/proprietar'
      preLoaderRoute: typeof ProprietarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmare': {
      id: '/confirmare'
      path: '/confirmare'
      fullPath: '/confirmare'
      preLoaderRoute: typeof ConfirmareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sali/': {
      id: '/sali/'
      path: '/'
      fullPath: '/sali/'
      preLoaderRoute: typeof SaliIndexRouteImport
      parentRoute: typeof SaliRoute
    }
    '/proprietar/': {
      id: '/proprietar/'
      path: '/'
      fullPath: '/proprietar/'
      preLoaderRoute: typeof ProprietarIndexRouteImport
      parentRoute: typeof ProprietarRoute
    }
    '/sali/$slug': {
      id: '/sali/$slug'
      path: '/$slug'
      fullPath: '/sali/$slug'
      preLoaderRoute: typeof SaliSlugRouteImport
      parentRoute: typeof SaliRoute
    }
    '/rezerva/$slug': {
      id: '/rezerva/$slug'
      path: '/rezerva/$slug'
      fullPath: '/rezerva/$slug'
      preLoaderRoute: typeof RezervaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietar/sali': {
      id: '/proprietar/sali'
      path: '/sali'
      fullPath: '/proprietar/sali'
      preLoaderRoute: typeof ProprietarSaliRouteImport
      parentRoute: typeof ProprietarRoute
    }
    '/proprietar/dashboard': {
      id: '/proprietar/dashboard'
      path: '/dashboard'
      fullPath: '/proprietar/dashboard'
      preLoaderRoute: typeof ProprietarDashboardRouteImport
      parentRoute: typeof ProprietarRoute
    }
    '/proprietar/calendar': {
      id: '/proprietar/calendar'
      path: '/calendar'
      fullPath: '/proprietar/calendar'
      preLoaderRoute: typeof ProprietarCalendarRouteImport
      parentRoute: typeof ProprietarRoute
    }
    '/proprietar/sali/': {
      id: '/proprietar/sali/'
      path: '/'
      fullPath: '/proprietar/sali/'
      preLoaderRoute: typeof ProprietarSaliIndexRouteImport
      parentRoute: typeof ProprietarSaliRoute
    }
    '/proprietar/sali/nou': {
      id: '/proprietar/sali/nou'
      path: '/nou'
      fullPath: '/proprietar/sali/nou'
      preLoaderRoute: typeof ProprietarSaliNouRouteImport
      parentRoute: typeof ProprietarSaliRoute
    }
    '/proprietar/sali/$id': {
      id: '/proprietar/sali/$id'
      path: '/$id'
      fullPath: '/proprietar/sali/$id'
      preLoaderRoute: typeof ProprietarSaliIdRouteImport
      parentRoute: typeof ProprietarSaliRoute
    }
    '/proprietar/sali/$id/edit': {
      id: '/proprietar/sali/$id/edit'
      path: '/edit'
      fullPath: '/proprietar/sali/$id/edit'
      preLoaderRoute: typeof ProprietarSaliIdEditRouteImport
      parentRoute: typeof ProprietarSaliIdRoute
    }
    '/proprietar/sali/$id/calendar': {
      id: '/proprietar/sali/$id/calendar'
      path: '/calendar'
      fullPath: '/proprietar/sali/$id/calendar'
      preLoaderRoute: typeof ProprietarSaliIdCalendarRouteImport
      parentRoute: typeof ProprietarSaliIdRoute
    }
  }
}

interface ProprietarSaliIdRouteChildren {
  ProprietarSaliIdCalendarRoute: typeof ProprietarSaliIdCalendarRoute
  ProprietarSaliIdEditRoute: typeof ProprietarSaliIdEditRoute
}

const ProprietarSaliIdRouteChildren: ProprietarSaliIdRouteChildren = {
  ProprietarSaliIdCalendarRoute: ProprietarSaliIdCalendarRoute,
  ProprietarSaliIdEditRoute: ProprietarSaliIdEditRoute,
}

const ProprietarSaliIdRouteWithChildren =
  ProprietarSaliIdRoute._addFileChildren(ProprietarSaliIdRouteChildren)

interface ProprietarSaliRouteChildren {
  ProprietarSaliIdRoute: typeof ProprietarSaliIdRouteWithChildren
  ProprietarSaliNouRoute: typeof ProprietarSaliNouRoute
  ProprietarSaliIndexRoute: typeof ProprietarSaliIndexRoute
}

const ProprietarSaliRouteChildren: ProprietarSaliRouteChildren = {
  ProprietarSaliIdRoute: ProprietarSaliIdRouteWithChildren,
  ProprietarSaliNouRoute: ProprietarSaliNouRoute,
  ProprietarSaliIndexRoute: ProprietarSaliIndexRoute,
}

const ProprietarSaliRouteWithChildren = ProprietarSaliRoute._addFileChildren(
  ProprietarSaliRouteChildren,
)

interface ProprietarRouteChildren {
  ProprietarCalendarRoute: typeof ProprietarCalendarRoute
  ProprietarDashboardRoute: typeof ProprietarDashboardRoute
  ProprietarSaliRoute: typeof ProprietarSaliRouteWithChildren
  ProprietarIndexRoute: typeof ProprietarIndexRoute
}

const ProprietarRouteChildren: ProprietarRouteChildren = {
  ProprietarCalendarRoute: ProprietarCalendarRoute,
  ProprietarDashboardRoute: ProprietarDashboardRoute,
  ProprietarSaliRoute: ProprietarSaliRouteWithChildren,
  ProprietarIndexRoute: ProprietarIndexRoute,
}

const ProprietarRouteWithChildren = ProprietarRoute._addFileChildren(
  ProprietarRouteChildren,
)

interface SaliRouteChildren {
  SaliSlugRoute: typeof SaliSlugRoute
  SaliIndexRoute: typeof SaliIndexRoute
}

const SaliRouteChildren: SaliRouteChildren = {
  SaliSlugRoute: SaliSlugRoute,
  SaliIndexRoute: SaliIndexRoute,
}

const SaliRouteWithChildren = SaliRoute._addFileChildren(SaliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmareRoute: ConfirmareRoute,
  LoginRoute: LoginRoute,
  ProprietarRoute: ProprietarRouteWithChildren,
  ResetParolaRoute: ResetParolaRoute,
  SaliRoute: SaliRouteWithChildren,
  SignupRoute: SignupRoute,
  RezervaSlugRoute: RezervaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
