/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaliIndexRouteImport } from './routes/sali.index'
import { Route as SaliSlugRouteImport } from './routes/sali.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaliIndexRoute = SaliIndexRouteImport.update({
  id: '/sali/',
  path: '/sali/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaliSlugRoute = SaliSlugRouteImport.update({
  id: '/sali/$slug',
  path: '/sali/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/sali/': typeof SaliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/sali': typeof SaliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/sali/': typeof SaliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/sali/$slug' | '/sali/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/sali/$slug' | '/sali'
  id: '__root__' | '/' | '/login' | '/signup' | '/sali/$slug' | '/sali/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SaliSlugRoute: typeof SaliSlugRoute
  SaliIndexRoute: typeof SaliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sali/': {
      id: '/sali/'
      path: '/sali'
      fullPath: '/sali/'
      preLoaderRoute: typeof SaliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sali/$slug': {
      id: '/sali/$slug'
      path: '/sali/$slug'
      fullPath: '/sali/$slug'
      preLoaderRoute: typeof SaliSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SaliSlugRoute: SaliSlugRoute,
  SaliIndexRoute: SaliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
