/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SaliRouteImport } from './routes/sali'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmareRouteImport } from './routes/confirmare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaliIndexRouteImport } from './routes/sali.index'
import { Route as SaliSlugRouteImport } from './routes/sali.$slug'
import { Route as RezervaSlugRouteImport } from './routes/rezerva.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SaliRoute = SaliRouteImport.update({
  id: '/sali',
  path: '/sali',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmareRoute = ConfirmareRouteImport.update({
  id: '/confirmare',
  path: '/confirmare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaliIndexRoute = SaliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaliRoute,
} as any)
const SaliSlugRoute = SaliSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SaliRoute,
} as any)
const RezervaSlugRoute = RezervaSlugRouteImport.update({
  id: '/rezerva/$slug',
  path: '/rezerva/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmare': typeof ConfirmareRoute
  '/login': typeof LoginRoute
  '/sali': typeof SaliRouteWithChildren
  '/signup': typeof SignupRoute
  '/rezerva/$slug': typeof RezervaSlugRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/sali/': typeof SaliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmare': typeof ConfirmareRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/rezerva/$slug': typeof RezervaSlugRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/sali': typeof SaliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmare': typeof ConfirmareRoute
  '/login': typeof LoginRoute
  '/sali': typeof SaliRouteWithChildren
  '/signup': typeof SignupRoute
  '/rezerva/$slug': typeof RezervaSlugRoute
  '/sali/$slug': typeof SaliSlugRoute
  '/sali/': typeof SaliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmare'
    | '/login'
    | '/sali'
    | '/signup'
    | '/rezerva/$slug'
    | '/sali/$slug'
    | '/sali/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmare'
    | '/login'
    | '/signup'
    | '/rezerva/$slug'
    | '/sali/$slug'
    | '/sali'
  id:
    | '__root__'
    | '/'
    | '/confirmare'
    | '/login'
    | '/sali'
    | '/signup'
    | '/rezerva/$slug'
    | '/sali/$slug'
    | '/sali/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmareRoute: typeof ConfirmareRoute
  LoginRoute: typeof LoginRoute
  SaliRoute: typeof SaliRouteWithChildren
  SignupRoute: typeof SignupRoute
  RezervaSlugRoute: typeof RezervaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sali': {
      id: '/sali'
      path: '/sali'
      fullPath: '/sali'
      preLoaderRoute: typeof SaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmare': {
      id: '/confirmare'
      path: '/confirmare'
      fullPath: '/confirmare'
      preLoaderRoute: typeof ConfirmareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sali/': {
      id: '/sali/'
      path: '/'
      fullPath: '/sali/'
      preLoaderRoute: typeof SaliIndexRouteImport
      parentRoute: typeof SaliRoute
    }
    '/sali/$slug': {
      id: '/sali/$slug'
      path: '/$slug'
      fullPath: '/sali/$slug'
      preLoaderRoute: typeof SaliSlugRouteImport
      parentRoute: typeof SaliRoute
    }
    '/rezerva/$slug': {
      id: '/rezerva/$slug'
      path: '/rezerva/$slug'
      fullPath: '/rezerva/$slug'
      preLoaderRoute: typeof RezervaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SaliRouteChildren {
  SaliSlugRoute: typeof SaliSlugRoute
  SaliIndexRoute: typeof SaliIndexRoute
}

const SaliRouteChildren: SaliRouteChildren = {
  SaliSlugRoute: SaliSlugRoute,
  SaliIndexRoute: SaliIndexRoute,
}

const SaliRouteWithChildren = SaliRoute._addFileChildren(SaliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmareRoute: ConfirmareRoute,
  LoginRoute: LoginRoute,
  SaliRoute: SaliRouteWithChildren,
  SignupRoute: SignupRoute,
  RezervaSlugRoute: RezervaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
